# Python Homework (NumPy, Pandas)

**Note**: You can create a Python file or a Jupyter Notebook file

<br>

<ins>Use markdown formatting for the following questions (e.g., bold lettering, bullet points, different font sizes, etc.)</ins>: 
1. What does Pandas stand for?
- Pandas has a reference to both "Panel Data" and "Python Data Analysis"
2. What are the 2 collections used in Pandas?
- Series and DataFrames
3. Name 4 things Pandas can do for us.
- Data Cleansing
- Data normalization
- Data visualization
- Data inspection
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
- inplace = True
5. What is a CSV?
- A Comma-separated values file is as a text file format that uses commas to separate values to be saved in a tablular format.
6. When cleaning data what values do we not like in our data?
- missing values, outliers, duplicate values, incorrectly formatted or irrelevant

<br>

#### **Please Complete this Coding Exercise:**

7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

In [5]:
import numpy as np

arr = np.arange(12).reshape((2,3,2))
print("The 3d array ...\n", arr)
print("The 3d array shape ...\n",arr.shape)

The 3d array ...
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
The 3d array shape ...
 (2, 3, 2)


8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

In [6]:
arr = np.linspace(0,20, num=6)
print(arr)

[ 0.  4.  8. 12. 16. 20.]


9. Make a Deep Copy of the above array

In [7]:
import copy
arr2 = copy.deepcopy(arr)
print(arr2)

[ 0.  4.  8. 12. 16. 20.]


10. Concatenate these 3 arrays into a new array named 'newArray'...
    ```pythons
            ([[25, 16]])
            ([[11, 2], [13, 4]])
            ([[7, 81], [5, 6], [11, 12]])
    ```

In [4]:
import numpy as np

arr1 = ([[25, 16]])
arr2 = ([[11, 2], [13, 4]])
arr3 = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arr1,arr2,arr3))
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


11. Sort 'newArray' in order into 'sortedArray'

In [5]:
sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

In [45]:
import numpy as np

arr = np.arange(24).reshape((4,3,2))
a, b, c, d = arr
print(a)
print(b)
print(c)
print(d)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[12 13]
 [14 15]
 [16 17]]
[[18 19]
 [20 21]
 [22 23]]


13. Combined and sort the following arrays into one called 'comboArray' ...

    ```python
        one = ([10, 11, 12, 13, 14, 15, 16, 17])
        two = ([20, 21, 22, 23, 24, 25, 26, 27])
        three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
    ```

In [15]:
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


14. Take 'comboArray' and perform the following slicing activities:
    - print sec1 - the 2nd element
    - print sec2 - all elements from the 3rd element to the last
    - print sec3 - all elements from the 4th to the 14th elements
    - print sec4 - the last 6 elements
    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
    - print sec6 - from #20 every even element to the end
    - print sec7 - from the last element moving forward, every 5th element.

In [25]:
sec1 = comboArray[1]
print("sec1 = ",sec1)
sec2 = comboArray[2:]
print("sec2 = ", sec2)
sec3 = comboArray[3:14]
print("sec3 = ", sec3)
sec4 = comboArray[-6:]
print("sec4 = " , sec4)
sec5 = comboArray[:-10]
print("sec5 = ", sec5)
sec6 = comboArray[-8::2]
print("sec6 = ", sec6)
sec7 = comboArray[::-5]
print("sec7 = ", sec7)

sec1 =  1
sec2 =  [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3 =  [ 3  4  5  6  7 10 11 12 13 14 15]
sec4 =  [22 23 24 25 26 27]
sec5 =  [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6 =  [20 22 24 26]
sec7 =  [27 22 15 10  3]


15. Using `Series`, create a `DataFrame` that looks like this:

    | Ingredients | Quantity | Unit |
    |----|----|----|
    | Flour | 4 | cups |
    | Milk | 1 | cup |
    | Eggs | 2 | large |
    | Spam | 1 | can |

    Name: Dinner, dtype: object

In [29]:
import numpy as np
import pandas as pd

ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name = "Ingredients")
quantity = pd.Series([4,1,2,1], name = "Quantity")
unit = pd.Series(["cups", "cup", "large", "can"], name = "Unit")
df = pd.concat([ingredients,quantity,unit], axis = 1)
print(df)

  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


16. Take this data and create a DataFrame named studentData
    ```Python
        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
        }
    ```

In [31]:
studentData = pd.DataFrame({'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
                        'Height': [5.1, 6.2, 5.1, 5.2],
                        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
                        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
                        'Age': [21, 23, 24, 21],
                        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
                        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
                    })
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


17. Add a new column to the DataFrame with the following deserts:
        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

In [32]:
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['deserts'] = deserts
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

In [33]:
studentData.sort_values(by = ['Name', 'address'], ascending = [True, True], inplace = True)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffels  
0     ice cream  
1  Cashew Fudge  


19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

    ```python
        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
    ```

In [34]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [42]:
vegetables = pd.DataFrame([["Pepper","Green"],["Carrot", "Orange"], ["Eggplant", "Purple"],["Cabbage", "Green"]], columns=["Name", "Color"])
vegetables.to_csv('vegetables.csv')
print(vegetables)
vegetables2 = pd.read_csv('vegetables.csv', index_col = 0)
vegetables2.loc[0,'Color'] = 'Red'
print(vegetables2)
vegetables2.to_csv('vegetables2.csv')

       Name   Color
0    Pepper   Green
1    Carrot  Orange
2  Eggplant  Purple
3   Cabbage   Green
       Name   Color
0    Pepper     Red
1    Carrot  Orange
2  Eggplant  Purple
3   Cabbage   Green
